# Generated by Django 3.1.7 on 2021-04-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmd',
            name='stdclass',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
